mlbench_datasets:
  - mlbench_function: hypercube
    params:
      n: [50, 200]
      d: [3, 5]
      sides: [3]
      sd: [0.2]
  - mlbench_function: shapes
    params:
      n: [100, 500]
  - mlbench_function: threenorm
    params:
      n: [100, 500]
      d: [5, 10, 20]
  - mlbench_function: waveform
    params:
      n: [100, 500]
  - mlbench_function: xor
    params:
      n: [500]
      d: [2, 5, 8]
  - mlbench_function: spirals
    params:
      n: [100, 500]
      sd: [0.2, 0.4]
      cycles: [1, 3, 5]
sklearn_datasets:
  load_iris: iris
  load_breast_cancer: breast_cancer
  load_wine: wine
settings:
  train_test_split_args:
    test_size: 0.25
    random_state: 42
