models:
  Decision Tree:
    random_seed: 42 # Add random seed parameter here
    steps:
      - name: imputer
        module: sklearn.impute
        class: SimpleImputer
        strategy: median
      - name: classifier
        module: sklearn.tree
        class: DecisionTreeClassifier
  Logistic Regression:
    random_seed: 42 # Add random seed parameter here
    steps:
      - name: imputer
        module: sklearn.impute
        class: SimpleImputer
        strategy: median
      - name: classifier
        module: sklearn.linear_model
        class: LogisticRegression
  KNN:
    random_seed: 42 # Add random seed parameter here
    steps:
      - name: imputer
        module: sklearn.impute
        class: SimpleImputer
        strategy: median
      - name: classifier
        module: sklearn.neighbors
        class: KNeighborsClassifier
  SVM:
    random_seed: 42 # Add random seed parameter here
    steps:
      - name: imputer
        module: sklearn.impute
        class: SimpleImputer
        strategy: median
      - name: classifier
        module: sklearn.svm
        class: SVC
