models:
  Decision Tree:
    steps:
      - name: imputer
        module: sklearn.impute
        class: SimpleImputer
        strategy: median
      - name: classifier
        module: sklearn.tree
        class: DecisionTreeClassifier
  Logistic Regression:
    steps:
      - name: imputer
        module: sklearn.impute
        class: SimpleImputer
        strategy: median
      - name: classifier
        module: sklearn.linear_model
        class: LogisticRegression
  KNN:
    steps:
      - name: imputer
        module: sklearn.impute
        class: SimpleImputer
        strategy: median
      - name: classifier
        module: sklearn.neighbors
        class: KNeighborsClassifier
